# This file was generated by GoReleaser. DO NOT EDIT.
cask "depscout" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "6974af1e74a291af6ffadf01fbfc4f4353aac059d485bdd2966418d7dd764706"
      url "https://github.com/AESalnikov/depscout/releases/download/v#{version}/depscout_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7551f6ae6287065d204020d1383beda819a066c880a4356941302b48521e6446"
      url "https://github.com/AESalnikov/depscout/releases/download/v#{version}/depscout_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a95a3ffebe74edf9d044bf5a4698aea4e612bbecf0b7eae7eb31ff3f9d161bd0"
      url "https://github.com/AESalnikov/depscout/releases/download/v#{version}/depscout_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f11282a17aa00ae13b6e2ad5c520694bfa68306ffb4b34fdbf1a98a0c5db4701"
      url "https://github.com/AESalnikov/depscout/releases/download/v#{version}/depscout_#{version}_linux_amd64.tar.gz"
    end
  end

  name "depscout"
  desc "Scout and update dependency versions in Gradle and Maven projects"
  homepage "https://github.com/AESalnikov/depscout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "depscout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/depscout"]
    end
  end

  # No zap stanza required
end
