# This file was generated by GoReleaser. DO NOT EDIT.
cask "depscout" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "e24add4e0d9aaea139d5d687d36d69ebe5fd15a40e411dcd7e06633014c5e452"
      url "https://github.com/AESalnikov/depscout/releases/download/v#{version}/depscout_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3c55e31d8cd4cb4bca70eb3ded632cf0f5d1ecb85b52727437102968a8c00a56"
      url "https://github.com/AESalnikov/depscout/releases/download/v#{version}/depscout_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "dda19ce3b2f4b6bdd9b92f3be814c0a20b2cd6b4325dfac8ee55a2f7f287c196"
      url "https://github.com/AESalnikov/depscout/releases/download/v#{version}/depscout_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b1e7aaceb5718578e0bb302e097d85d6b728d446aad33c6dba0b3596fc192956"
      url "https://github.com/AESalnikov/depscout/releases/download/v#{version}/depscout_#{version}_linux_amd64.tar.gz"
    end
  end

  name "depscout"
  desc "Scout and update dependency versions in Gradle and Maven projects"
  homepage "https://github.com/AESalnikov/depscout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "depscout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/depscout"]
    end
  end

  # No zap stanza required
end
