# This file was generated by GoReleaser. DO NOT EDIT.
cask "depscout" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "89066a34e5b62078023cbf27c695821efe741ac11f49b26110b68cfffcafdb9d"
      url "https://github.com/AESalnikov/depscout/releases/download/v#{version}/depscout_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4bf4321950c6e767a415b9a4d00134ddbb4780bae36cdb2da1e591ea20c5843d"
      url "https://github.com/AESalnikov/depscout/releases/download/v#{version}/depscout_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "414eb3f6b7f51ecff5bcc0b942eb7bf75d5f62f16e3953b2a61606c86804addb"
      url "https://github.com/AESalnikov/depscout/releases/download/v#{version}/depscout_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "06869b9e59652a44cc6701e6fb953430d4b72a7574b0e24ce2f72fc2f52d6e5e"
      url "https://github.com/AESalnikov/depscout/releases/download/v#{version}/depscout_#{version}_linux_amd64.tar.gz"
    end
  end

  name "depscout"
  desc "Scout and update dependency versions in Gradle and Maven projects"
  homepage "https://github.com/AESalnikov/depscout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "depscout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/depscout"]
    end
  end

  # No zap stanza required
end
